<?php

namespace Database\Seeders;

use App\Models\TimelineEvent;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

class TimelineEventCustomSeeder extends Seeder
{
    public function run(): void
    {

        $events = [

            [
                'title' => 'Chris Watts and Shanann Rzucek marry',
                'description' => 'Christopher Watts and Shanann Rzucek married in North Carolina.',
                'occurred_at' => '2012-11-03 14:00:00',
                'date_label' => null,
                'time_label' => null,
                'type' => 'background',
                'accuracy' => 'exact',
                'is_key_event' => false,
                'importance' => 3,
                'icon' => 'heart',
                'color' => 'gray',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Birth of Bella Watts',
                'description' => 'Bella Marie Watts was born.',
                'occurred_at' => '2013-12-17 12:00:00',
                'date_label' => null,
                'time_label' => null,
                'type' => 'family',
                'accuracy' => 'exact',
                'is_key_event' => false,
                'importance' => 2,
                'icon' => 'baby',
                'color' => 'gray',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Watts family moves to Frederick, Colorado',
                'description' => 'The family relocated to Frederick, Colorado.',
                'occurred_at' => '2015-06-01 12:00:00',
                'date_label' => '2015',
                'time_label' => null,
                'type' => 'background',
                'accuracy' => 'approximate',
                'is_key_event' => false,
                'importance' => 2,
                'icon' => 'home',
                'color' => 'gray',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Birth of Celeste Watts',
                'description' => 'Celeste "CeCe" Watts was born.',
                'occurred_at' => '2015-07-17 12:00:00',
                'date_label' => null,
                'time_label' => null,
                'type' => 'family',
                'accuracy' => 'exact',
                'is_key_event' => false,
                'importance' => 2,
                'icon' => 'baby',
                'color' => 'gray',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Chris begins affair with Nichol Kessinger',
                'description' => 'Chris Watts began a relationship with coworker Nichol Kessinger.',
                'occurred_at' => '2018-06-01 12:00:00',
                'date_label' => 'June 2018',
                'time_label' => null,
                'type' => 'relationship',
                'accuracy' => 'approximate',
                'is_key_event' => false,
                'importance' => 4,
                'icon' => 'heart-crack',
                'color' => 'orange',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Shanann announces third pregnancy',
                'description' => 'Shanann publicly announced that she was pregnant with the couple’s third child, Nico.',
                'occurred_at' => '2018-06-11 10:00:00',
                'date_label' => null,
                'time_label' => null,
                'type' => 'family',
                'accuracy' => 'exact',
                'is_key_event' => false,
                'importance' => 3,
                'icon' => 'baby',
                'color' => 'blue',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Shanann leaves for Arizona business trip',
                'description' => 'Shanann traveled to Arizona for a Thrive convention.',
                'occurred_at' => '2018-08-09 08:00:00',
                'date_label' => null,
                'time_label' => null,
                'type' => 'background',
                'accuracy' => 'exact',
                'is_key_event' => false,
                'importance' => 2,
                'icon' => 'briefcase',
                'color' => 'gray',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Shanann returns home from Arizona',
                'description' => 'A friend drove Shanann home from Denver International Airport.',
                'occurred_at' => '2018-08-13 01:48:00',
                'date_label' => null,
                'time_label' => null,
                'type' => 'timeline',
                'accuracy' => 'exact',
                'is_key_event' => true,
                'importance' => 5,
                'icon' => 'car',
                'color' => 'blue',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Murders occur inside the Watts home',
                'description' => 'Shanann, Bella, Celeste and unborn child Nico were killed.',
                'occurred_at' => '2018-08-13 04:00:00',
                'date_label' => null,
                'time_label' => 'Early morning',
                'type' => 'murder',
                'accuracy' => 'approximate',
                'is_key_event' => true,
                'importance' => 5,
                'icon' => 'skull',
                'color' => 'red',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Chris leaves home for Cervi 319 oil site',
                'description' => 'Chris drove his work truck to the Anadarko Petroleum site.',
                'occurred_at' => '2018-08-13 05:27:00',
                'date_label' => null,
                'time_label' => null,
                'type' => 'timeline',
                'accuracy' => 'exact',
                'is_key_event' => true,
                'importance' => 5,
                'icon' => 'truck',
                'color' => 'blue',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Bodies hidden at Cervi 319',
                'description' => 'Shanann was buried in a shallow grave and Bella and Celeste were placed in oil tanks.',
                'occurred_at' => '2018-08-13 06:30:00',
                'date_label' => null,
                'time_label' => 'Morning',
                'type' => 'crime-scene',
                'accuracy' => 'approximate',
                'is_key_event' => true,
                'importance' => 5,
                'icon' => 'map-pin',
                'color' => 'red',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Nicole Atkinson reports Shanann missing',
                'description' => 'Concerned friend Nicole Atkinson requested a welfare check.',
                'occurred_at' => '2018-08-13 13:40:00',
                'date_label' => null,
                'time_label' => null,
                'type' => 'investigation',
                'accuracy' => 'exact',
                'is_key_event' => true,
                'importance' => 5,
                'icon' => 'phone',
                'color' => 'orange',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Police conduct welfare check',
                'description' => 'Frederick police officers arrived at the Watts residence.',
                'occurred_at' => '2018-08-13 14:00:00',
                'date_label' => null,
                'time_label' => null,
                'type' => 'investigation',
                'accuracy' => 'exact',
                'is_key_event' => true,
                'importance' => 5,
                'icon' => 'shield',
                'color' => 'orange',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Neighbor security footage reviewed',
                'description' => 'Investigators reviewed Nate Trinastich’s surveillance footage.',
                'occurred_at' => '2018-08-13 17:00:00',
                'date_label' => null,
                'time_label' => null,
                'type' => 'evidence',
                'accuracy' => 'exact',
                'is_key_event' => true,
                'importance' => 5,
                'icon' => 'camera',
                'color' => 'purple',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Chris gives television interview',
                'description' => 'Chris Watts appealed for his family’s return in local media interviews.',
                'occurred_at' => '2018-08-14 19:00:00',
                'date_label' => null,
                'time_label' => null,
                'type' => 'media',
                'accuracy' => 'exact',
                'is_key_event' => true,
                'importance' => 4,
                'icon' => 'tv',
                'color' => 'blue',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Chris fails polygraph examination',
                'description' => 'Chris Watts failed a polygraph administered by investigators.',
                'occurred_at' => '2018-08-15 13:30:00',
                'date_label' => null,
                'time_label' => null,
                'type' => 'evidence',
                'accuracy' => 'exact',
                'is_key_event' => true,
                'importance' => 5,
                'icon' => 'activity',
                'color' => 'purple',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Chris confesses to killing Shanann',
                'description' => 'Chris initially claimed Shanann killed the children before admitting responsibility.',
                'occurred_at' => '2018-08-15 17:00:00',
                'date_label' => null,
                'time_label' => null,
                'type' => 'confession',
                'accuracy' => 'exact',
                'is_key_event' => true,
                'importance' => 5,
                'icon' => 'message-square',
                'color' => 'red',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Chris Watts arrested',
                'description' => 'Chris Watts was taken into custody.',
                'occurred_at' => '2018-08-15 22:00:00',
                'date_label' => null,
                'time_label' => null,
                'type' => 'arrest',
                'accuracy' => 'exact',
                'is_key_event' => true,
                'importance' => 5,
                'icon' => 'handcuffs',
                'color' => 'orange',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Bodies recovered at Cervi 319',
                'description' => 'Investigators located Shanann, Bella and Celeste.',
                'occurred_at' => '2018-08-16 14:00:00',
                'date_label' => null,
                'time_label' => null,
                'type' => 'recovery',
                'accuracy' => 'exact',
                'is_key_event' => true,
                'importance' => 5,
                'icon' => 'map-pin',
                'color' => 'red',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Chris pleads guilty',
                'description' => 'Chris Watts pleaded guilty to all murders and related charges.',
                'occurred_at' => '2018-11-06 15:00:00',
                'date_label' => null,
                'time_label' => null,
                'type' => 'plea',
                'accuracy' => 'exact',
                'is_key_event' => true,
                'importance' => 5,
                'icon' => 'file-check',
                'color' => 'green',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Chris Watts sentenced to life imprisonment',
                'description' => 'Watts received multiple life sentences without parole.',
                'occurred_at' => '2018-11-19 14:00:00',
                'date_label' => null,
                'time_label' => null,
                'type' => 'sentencing',
                'accuracy' => 'exact',
                'is_key_event' => true,
                'importance' => 5,
                'icon' => 'scale',
                'color' => 'red',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Transferred to Wisconsin prison',
                'description' => 'Chris Watts was moved to Dodge Correctional Institution.',
                'occurred_at' => '2018-12-03 12:00:00',
                'date_label' => null,
                'time_label' => null,
                'type' => 'custody',
                'accuracy' => 'exact',
                'is_key_event' => false,
                'importance' => 2,
                'icon' => 'lock',
                'color' => 'gray',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Investigators conduct prison interview',
                'description' => 'Watts gave a more detailed account of the murders during a prison interview.',
                'occurred_at' => '2019-02-18 10:00:00',
                'date_label' => null,
                'time_label' => null,
                'type' => 'confession',
                'accuracy' => 'exact',
                'is_key_event' => true,
                'importance' => 4,
                'icon' => 'mic',
                'color' => 'purple',
                'source_name' => null,
                'source_url' => null,
            ],

            [
                'title' => 'Netflix releases "American Murder: The Family Next Door"',
                'description' => 'The documentary renewed public interest in the case.',
                'occurred_at' => '2020-09-30 12:00:00',
                'date_label' => null,
                'time_label' => null,
                'type' => 'media',
                'accuracy' => 'exact',
                'is_key_event' => false,
                'importance' => 2,
                'icon' => 'film',
                'color' => 'blue',
                'source_name' => 'Netflix',
                'source_url' => null,
            ],

        ];

        foreach ($events as $index => $event) {

            TimelineEvent::create([
                'hex' => strtoupper(Str::random(11)),

                'timeline_id' => 2,
                'parent_event_id' => null,

                'title' => $event['title'],
                'description' => $event['description'] ?? null,

                'occurred_at' => isset($event['occurred_at'])
                    ? Carbon::parse($event['occurred_at'])
                    : null,

                'date_label' => $event['date_label'] ?? null,
                'time_label' => $event['time_label'] ?? null,

                'sort_order' => $index + 1,

                'type' => $event['type'] ?? null,
                'icon' => $event['icon'] ?? null,
                'color' => $event['color'] ?? null,

                'source_name' => $event['source_name'] ?? null,
                'source_url' => $event['source_url'] ?? null,

                'is_published' => true,
                'published_at' => now(),
            ]);
        }
    }
}
